// Registro dos estilos visuais do Coacus (ui-style-*). `fx: true` => existe styles/fx/<slug>.js
const g = (group, items) => items.map(([slug, name, desc, fx = false]) => ({ slug, name, desc, group, fx }));

export const STYLES = [
  ...g('Limpo e funcional', [
    ['swiss-web-minimalism', 'Swiss Web Minimalism', 'Grid rígido, tipografia neutra, muito espaço em branco.'],
    ['flat-design', 'Flat Design', 'Cores sólidas, sem sombras nem gradientes.'],
    ['calm-quiet-ui', 'Calm / Quiet UI', 'Interface silenciosa, baixo estímulo, foco no conteúdo.'],
    ['linear-saas', 'Linear SaaS', 'Dark UI refinada de produto SaaS, bordas sutis.'],
    ['metro-modern-ui', 'Metro Modern UI', 'Blocos tipográficos e cores chapadas à la Metro.'],
    ['material-you', 'Material You', 'Cores dinâmicas, formas arredondadas e tonais.'],
    ['card-based-ui', 'Card-based UI', 'Tudo organizado em cartões modulares.'],
    ['bento-grid', 'Bento Grid', 'Grade de blocos assimétricos estilo bento.'],
    ['dark-mode-first', 'Dark Mode First', 'Projetado primeiro para o escuro.'],
    ['split-screen-dualism', 'Split-Screen Dualism', 'Tela dividida em duas metades com polaridade visual.'],
    ['blueprint-cad-schematic', 'Blueprint & CAD Schematic', 'Linhas de desenho técnico em ciano e grid milimétrico.'],
  ]),
  ...g('Superfície e materiais', [
    ['glassmorphism', 'Glassmorphism & Spatial UI', 'Vidro fosco, blur, reflexos especulares e elevação espacial visionOS.'],
    ['neumorphism', 'Neumorphism', 'Relevo suave extrudado do fundo.'],
    ['claymorphism', 'Claymorphism & Stop-Motion', 'Massinha 3D inflada, sombras internas e charme tátil de plasticina.'],
    ['skeuomorphism', 'Skeuomorphism & Aqua', 'Texturas físicas, dials de metal usinado e brilho aquático Y2K.'],
    ['frutiger-aero', 'Frutiger Aero', 'Brilho aquático, bolhas e natureza otimista.'],
    ['aurora-mesh-gradient', 'Aurora / Mesh Gradient', 'Gradientes de malha em movimento suave.'],
    ['gradient-duotone', 'Gradient & Duotone', 'Duas cores dominantes e gradientes ousados.'],
    ['grain-noise-texture', 'Grain / Noise Texture', 'Granulação e ruído tátil.'],
    ['holographic-foil-iridescent', 'Holographic Foil', 'Reflexos perolizados, arco-íris prismático e cromo.'],
  ]),
  ...g('Brutalista e rebelde', [
    ['neo-brutalism', 'Neo-Brutalism', 'Bordas grossas, sombras duras, cores vivas.'],
    ['web-brutalism', 'Web Brutalism & Data-Dense', 'Crueza HTML, tabelas de alta densidade e estética de terminal.'],
    ['brutalist-monochrome', 'Brutalist Monochrome & Tactile', 'Preto e branco absoluto, linhas milimétricas e scaffolds de precisão.'],
    ['acid-anti-design', 'Acid / Anti-design', 'Caos intencional, cores ácidas.'],
    ['maximalism', 'Maximalism', 'Mais é mais: padrões, cores e camadas.'],
    ['broken-grid', 'Broken Grid', 'Grade quebrada, sobreposições assimétricas.'],
    ['glitch', 'Glitch', 'Falhas digitais, RGB split e distorção.', true],
    ['memphis', 'Memphis', 'Formas geométricas e confetes dos anos 80.'],
    ['weirdcore-dreamcore', 'Weirdcore / Dreamcore', 'Espaços liminares surreais, baixa fidelidade e nostalgia lo-fi.'],
  ]),
  ...g('Tipografia e editorial', [
    ['editorial-archive-luxury', 'Editorial Luxury & Gallery', 'Revista de luxo, serifas monumentais e galerias horizontais.'],
    ['analog-newspaper-broadsheet', 'Broadsheet Newspaper', 'Diagramação clássica de jornal diário, colunas estritas e capitulares.'],
    ['expressive-variable-typography', 'Variable Type & Anti-Hero', 'Fontes variáveis em escala colossal, glifo como protagonista.'],
    ['kinetic-typography', 'Kinetic Typography & Ticker', 'Texto em movimento contínuo, revelações mascaradas e fitas de ticker.', true],
    ['risograph-zine', 'Risograph / Zine', 'Impressão riso, sobreposição de tintas.'],
    ['collage-scrapbook', 'Collage, Scrapbook & Dada', 'Recortes, fitas, colagem tátil e tipografia de manifesto dadaísta.'],
    ['hand-drawn-sketch', 'Hand-drawn / Sketch', 'Traços feitos à mão.'],
  ]),
  ...g('Movimentos históricos e retrô', [
    ['art-deco', 'Art Deco', 'Simetria, dourado e geometria elegante.'],
    ['art-nouveau-arts-crafts', 'Art Nouveau / Arts & Crafts', 'Linhas orgânicas e ornamento artesanal.'],
    ['bauhaus', 'Bauhaus', 'Formas primárias e funcionalismo.'],
    ['de-stijl', 'De Stijl', 'Linhas pretas e cores primárias.'],
    ['constructivism-propaganda', 'Constructivism Propaganda', 'Diagonais 45°, vermelho/preto/bege e cartaz soviético.'],
    ['pop-art-halftone', 'Pop Art Halftone', 'Retícula Ben-Day de quadrinhos, contornos pretos e cores CMYK.'],
    ['psychedelic-60s', '1960s Psychedelic', 'Tipografia líquida derretida, cores vibrantes e pôster de San Francisco.'],
    ['mid-century-modern', 'Mid-century Modern', 'Meados do século XX, tons terrosos.'],
    ['y2k-revival', 'Y2K Revival', 'Cromado, translúcido e futurismo 2000.'],
    ['vaporwave-synthwave', 'Vaporwave / Synthwave', 'Neon rosa-ciano e grade retrô.'],
    ['indie-web-revival', 'Indie Web Revival', 'Web pessoal anos 90 revisitada.'],
    ['retro-computing-pixel', 'Retro Computing / Pixel', 'Pixel art e computadores clássicos.'],
    ['terminal-tui', 'Terminal / TUI', 'Interface de terminal em texto.', true],
    ['cassette-futurism', 'Cassette Futurism', 'Ficção analógica anos 70/80, fósforo CRT e painéis industriais beges.'],
    ['dungeon-synth-dark-fantasy', 'Dungeon Synth Fantasy', 'Dark fantasy medieval, pedras de cripta, runas e ouro envelhecido.'],
  ]),
  ...g('Punks e ficção científica', [
    ['cyberpunk', 'Cyberpunk & Tactical HUD', 'Neon-noir, chuva, alta tecnologia decadente e painéis de HUD.'],
    ['atompunk', 'Atompunk & Retro-Futurism', 'Era atômica, Googie, órbitas e otimismo espacial.'],
    ['biopunk', 'Biopunk', 'Biotecnologia, tons orgânicos e laboratório.'],
    ['clockpunk', 'Clockpunk', 'Engrenagens e mecanismos de relojoaria.'],
    ['dieselpunk', 'Dieselpunk', 'Metal industrial entre-guerras.'],
    ['gothicpunk', 'Gothicpunk', 'Gótico sombrio e dramático.'],
    ['lunarpunk', 'Lunarpunk', 'Noite, prata e misticismo digital.'],
    ['nanopunk', 'Nanopunk', 'Microescala, partículas e precisão.'],
    ['sandalpunk', 'Sandalpunk', 'Mundo antigo e mediterrâneo reimaginado.'],
    ['silkpunk', 'Silkpunk', 'Ficção especulativa da Ásia Oriental, bambu, seda, origami e nanquim.'],
    ['solarpunk', 'Solarpunk & Biomorphic', 'Futuro verde solar, linho pastoral e algoritmos de crescimento biológico.'],
    ['steampunk', 'Steampunk', 'Vapor, latão e vitoriana mecânica.'],
  ]),
  ...g('Imersivo e movimento', [
    ['3d-immersive-webgl', '3D Immersive / WebGL', 'Cena 3D interativa em WebGL.', true],
    ['parallax-scrolling', 'Parallax Scrolling', 'Camadas com profundidade ao rolar.', true],
    ['scrollytelling', 'Scrollytelling & Long Scroll', 'Narrativa guiada pela rolagem e página única contínua.', true],
    ['micro-interactions', 'Micro-interactions', 'Pequenas animações de feedback.', true],
    ['isometric', 'Isometric', 'Projeção isométrica.'],
    ['fluid-liquid-morph', 'Fluid Liquid Morph', 'Efeito metaball, física de fluidos viscosos e transições de gelatina.', true],
    ['ai-native-generative-ui', 'AI-native / Generative UI', 'Interface que se compõe a partir de intenção.', true],
    ['organic-biophilic', 'Organic / Biophilic', 'Formas e texturas da natureza.'],
    ['kawaii-pastel-soft', 'Kawaii Pastel Soft', 'Formas acolchoadas de marshmallow, cores pastéis e carisma fofo.'],
  ]),
];
