// Registro dos estilos visuais do Coacus (ui-style-*). `fx: true` => existe styles/fx/<slug>.js
const g = (group, items) => items.map(([slug, name, desc, fx = false]) => ({ slug, name, desc, group, fx }));

export const STYLES = [
  ...g('Limpo e funcional', [
    ['swiss-web-minimalism', 'Swiss Web Minimalism', 'Grid rígido, tipografia neutra, muito espaço em branco.'],
    ['flat-design', 'Flat Design', 'Cores sólidas, sem sombras nem gradientes.'],
    ['calm-quiet-ui', 'Calm / Quiet UI', 'Interface silenciosa, baixo estímulo, foco no conteúdo.'],
    ['linear-saas', 'Linear SaaS', 'Dark UI refinada de produto SaaS, bordas sutis.'],
    ['metro-modern-ui', 'Metro Modern UI', 'Blocos tipográficos e cores chapadas à la Metro.'],
    ['material-you', 'Material You', 'Cores dinâmicas, formas arredondadas e tonais.'],
    ['card-based-ui', 'Card-based UI', 'Tudo organizado em cartões modulares.'],
    ['bento-grid', 'Bento Grid', 'Grade de blocos assimétricos estilo bento.'],
    ['dark-mode-first', 'Dark Mode First', 'Projetado primeiro para o escuro.'],
  ]),
  ...g('Superfície e materiais', [
    ['glassmorphism', 'Glassmorphism', 'Vidro fosco, blur e transparência.'],
    ['neumorphism', 'Neumorphism', 'Relevo suave extrudado do fundo.'],
    ['claymorphism', 'Claymorphism', 'Massinha 3D, inflado e macio.'],
    ['skeuomorphism', 'Skeuomorphism', 'Texturas e materiais do mundo real.'],
    ['frutiger-aero', 'Frutiger Aero', 'Brilho aquático, bolhas e natureza otimista.'],
    ['aurora-mesh-gradient', 'Aurora / Mesh Gradient', 'Gradientes de malha em movimento suave.'],
    ['gradient-duotone', 'Gradient & Duotone', 'Duas cores dominantes e gradientes ousados.'],
    ['grain-noise-texture', 'Grain / Noise Texture', 'Granulação e ruído tátil.'],
  ]),
  ...g('Brutalista e rebelde', [
    ['neo-brutalism', 'Neo-Brutalism', 'Bordas grossas, sombras duras, cores vivas.'],
    ['web-brutalism', 'Web Brutalism', 'Crueza HTML, monoespaçada, sem adornos.'],
    ['tactile-brutalism', 'Tactile Brutalism', 'Brutalismo com peso físico e textura.'],
    ['acid-anti-design', 'Acid / Anti-design', 'Caos intencional, cores ácidas.'],
    ['maximalism', 'Maximalism', 'Mais é mais: padrões, cores e camadas.'],
    ['broken-grid', 'Broken Grid', 'Grade quebrada, sobreposições assimétricas.'],
    ['glitch', 'Glitch', 'Falhas digitais, RGB split e distorção.', true],
    ['memphis', 'Memphis', 'Formas geométricas e confetes dos anos 80.'],
  ]),
  ...g('Tipografia e editorial', [
    ['editorial-archive-luxury', 'Editorial / Archive Luxury', 'Revista de luxo, serifas e arquivo.'],
    ['expressive-variable-typography', 'Expressive Variable Typography', 'Fontes variáveis como protagonista.'],
    ['kinetic-typography', 'Kinetic Typography', 'Texto em movimento.', true],
    ['risograph-zine', 'Risograph / Zine', 'Impressão riso, sobreposição de tintas.'],
    ['collage-scrapbook', 'Collage / Scrapbook', 'Recortes, fitas e colagem.'],
    ['hand-drawn-sketch', 'Hand-drawn / Sketch', 'Traços feitos à mão.'],
  ]),
  ...g('Movimentos históricos e retrô', [
    ['art-deco', 'Art Deco', 'Simetria, dourado e geometria elegante.'],
    ['art-nouveau-arts-crafts', 'Art Nouveau / Arts & Crafts', 'Linhas orgânicas e ornamento artesanal.'],
    ['bauhaus', 'Bauhaus', 'Formas primárias e funcionalismo.'],
    ['de-stijl', 'De Stijl', 'Linhas pretas e cores primárias.'],
    ['mid-century-modern', 'Mid-century Modern', 'Meados do século XX, tons terrosos.'],
    ['y2k-revival', 'Y2K Revival', 'Cromado, translúcido e futurismo 2000.'],
    ['vaporwave-synthwave', 'Vaporwave / Synthwave', 'Neon rosa-ciano e grade retrô.'],
    ['indie-web-revival', 'Indie Web Revival', 'Web pessoal anos 90 revisitada.'],
    ['retro-computing-pixel', 'Retro Computing / Pixel', 'Pixel art e computadores clássicos.'],
    ['terminal-tui', 'Terminal / TUI', 'Interface de terminal em texto.', true],
  ]),
  ...g('Punks e ficção científica', [
    ['cyberpunk', 'Cyberpunk', 'Neon, chuva e alta tecnologia decadente.'],
    ['cyberpunk-hud', 'Cyberpunk HUD', 'Painéis de HUD táticos.'],
    ['atompunk', 'Atompunk', 'Era atômica e otimismo espacial.'],
    ['retro-futurism-atompunk', 'Retro-futurism', 'O futuro como imaginado no passado.'],
    ['biopunk', 'Biopunk', 'Biotecnologia, tons orgânicos e laboratório.'],
    ['clockpunk', 'Clockpunk', 'Engrenagens e mecanismos de relojoaria.'],
    ['dieselpunk', 'Dieselpunk', 'Metal industrial entre-guerras.'],
    ['gothicpunk', 'Gothicpunk', 'Gótico sombrio e dramático.'],
    ['lunarpunk', 'Lunarpunk', 'Noite, prata e misticismo digital.'],
    ['nanopunk', 'Nanopunk', 'Microescala, partículas e precisão.'],
    ['sandalpunk', 'Sandalpunk', 'Mundo antigo e mediterrâneo reimaginado.'],
    ['solarpunk', 'Solarpunk', 'Futuro verde, solar e esperançoso.'],
    ['steampunk', 'Steampunk', 'Vapor, latão e vitoriana mecânica.'],
  ]),
  ...g('Imersivo e movimento', [
    ['3d-immersive-webgl', '3D Immersive / WebGL', 'Cena 3D interativa em WebGL.', true],
    ['parallax-scrolling', 'Parallax Scrolling', 'Camadas com profundidade ao rolar.', true],
    ['scrollytelling', 'Scrollytelling', 'Narrativa guiada pela rolagem.', true],
    ['one-page-long-scroll', 'One-page Long Scroll', 'Página única de rolagem longa.'],
    ['micro-interactions', 'Micro-interactions', 'Pequenas animações de feedback.', true],
    ['isometric', 'Isometric', 'Projeção isométrica.'],
    ['ai-native-generative-ui', 'AI-native / Generative UI', 'Interface que se compõe a partir de intenção.', true],
    ['organic-biophilic', 'Organic / Biophilic', 'Formas e texturas da natureza.'],
  ]),
];
